spring.application.name=library-management
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=LMSVer2;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true